[package]
name = "iridium-rust-client-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iridium-rust-client-lib = { path = "./iridium-rust-client-lib" }
warp = "0.3.5"
tokio = "1.32.0"

